import React from 'react';
import { useCurrentUserAdmin } from '@/lib/server/helperServer';
import ClientOnly from '@/components/ClientOnly';
import AdminSideBar from '@/components/admin/AdminSideBar';
import { redirect } from 'next/navigation';
import db from '@/lib/server/prismadb';

export const metadata = {
  title: 'Admin Create Next App',
  description: 'Generated by create next app',
}

export default async function AdminRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const user = await useCurrentUserAdmin()

  if (!user) {
    redirect('/admin/login')
  }

  return (
    <div className="w-full h-screen flex bg-gray-100">
      <div className="flex-none h-full">
        <AdminSideBar user={user} />
      </div>
      <div className="flex-grow min-w-0 h-full">
        {children}
      </div>
    </div>
  )
}